route:
  group_by: ['alertname','cluster','service']
  group_wait: 1m
  group_interval: 1m
  repeat_interval: 2m
  receiver: 'telegram'
receivers:
  - name: 'telegram'
    telegram_configs:
    - bot_token: '6072750240:AAH7_ymRs8Q03uslgSEYsi6VUAkgjxLwokQ'
      api_url: 'https://api.telegram.org'
      chat_id: -874263461
      message:  "Alertname: {{ .GroupLabels.alertname }}\nSeverity: {{ .CommonLabels.severity }}\n{{ range .Alerts }}Description: {{ .Annotations.description }}\n{{ end }}"
      parse_mode: ''
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
